baseURL: "https://dfwmobile214.github.io"
theme: "up-business-theme"
languageCode: "en-us"

title: "DFW Mobile Apps"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "DFW Mobile Apps"
  description: "We specialize in providing services to desing websites, applications, build and maintain business for customers."
  images: 
    - "images/hero-image.png"

  logo: "images/hero-image.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - " 8035 E R L Thornton Fwy, Dallas, TX 75228"

  contact:
    - "morales2480@gamail.com"
    - "777.555.0119"

  copyright: "© 2022 Linear DevOps  All Rights Reserved"

  postProcess: false

menus:
  main:
    - name: "Home"
      url: "/#home"
      weight: 1

    - name: "Services"
      url: "/#services"
      weight: 2

    - name: "Contact"
      url: "/#contact"
      weight: 3


    - name: "Blog"
      url: "/blog"
      weight: 5

  buttons:
    - name: "Book a call"
      url: "/#"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#home"
      weight: 1

    - name: "Services"
      url: "/#services"
      weight: 2

    - name: "Contact"
      url: "/#contact"
      weight: 3


    - name: "Blog"
      url: "/blog"
      weight: 5


taxonomies:
  series: "series"
  tags: "tags"
